const TEN_MINUTES = "600000";
const FIVE_SECONDS = "5000";
const APP_CACHE_V1_KEY = "APP_CACHE_V1_KEY ";
const LOAD_TIME = parseInt(process.env.REACT_APP_LOAD_TIME || FIVE_SECONDS);
export {
    APP_CACHE_V1_KEY,
    FIVE_SECONDS,
    LOAD_TIME,
    TEN_MINUTES,
}